spring:
  security:
    oauth2:
      client:
        registration:
          sample:
            provider: sample
            client-id: client
            client-secret: gXUUp9xQ7bvzdBiFGZXXvcKhWoE933DM
            scope:
              - openid
              - profile
        provider:
          sample:
            issuer-uri: http://localhost:8080/realms/master
server:
  port: 8090
logging:
  level:
    org:
      springframework:
        security: trace
debug: true