server:
  port: 8085
debug: true
spring:
  mvc:
    log-request-details: true
  codec:
    log-request-details: true
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8085/
logging:
  level:
    org:
      springframework:
        security: trace





